Unleash/unleash-proxy-client-swift

Package.swift, README.md, UnleashProxyClientSwift.podspec
I am evaluating the use of Unleash in a multi platform project and realized I couldn't use the SDK as is on tvOS or watchOS. I got some warnings about versioning which my app was already above the minimum targets there (tvOS 14, and watchOS 7). 
I took a quick look thought the code and didn't notice anything complex that would prevent using the SDK on either platform. So I went ahead and added both platforms to the package file which seems to fix things. 
Hopefully this is an acceptable change! I'm excited to try out Unleash in my app.
There really isn't much going on here, the main change is just the new tvOS and watchOS declarations in the package and podspec files.
=> Add support for tvOS and watchOS

UnleashProxyClientSwift.podspec
=> fix: update podspec

UnleashProxyClientSwift.podspec
=> fix: revert podspec version

README.md
Adds some notes on how to release the project
=> docs: add notes on how to release the project

UnleashProxyClientSwift.podspec
Bumps the podspec of this package
Closes #
=> chore: bump podspec

Package.swift, README.md, Sources/UnleashProxyClientSwift/UnleashProxyClientSwift.swift, Tests/UnleashProxyClientSwiftTests/UnleashProxyClientSwiftTests.swift, Tests/UnleashProxyClientSwiftTests/testUtils.swift, UnleashProxyClientSwift.podspec
Downgrade to iOS version 12
Closes #
=> Downgrade unleash to iOS v12

.gitignore, Sources/UnleashProxyClientSwift/Metrics.swift, Tests/UnleashProxyClientSwiftTests/MetricsTests.swift
Ported metrics from the flutter SDK: https://github.com/Unleash/unleash_proxy_client_flutter/blob/main/lib/metrics.dart
Currently metrics are not plugged into the main code. It will be done as a separate PR to keep it manageable.
=> feat: metrics

.gitignore, README.md, Sources/UnleashProxyClientSwift/Metrics.swift, Sources/UnleashProxyClientSwift/UnleashProxyClientSwift.swift, Tests/UnleashProxyClientSwiftTests/MetricsTests.swift, Tests/UnleashProxyClientSwiftTests/MockMetrics.swift, Tests/UnleashProxyClientSwiftTests/UnleashProxyClientSwiftTests.swift, Tests/UnleashProxyClientSwiftTests/testUtils.swift
Plugging in metrics into the unleash client and added more tests around metrics corner cases
Followup to https://github.com/Unleash/unleash-proxy-client-swift/pull/36. We need to merge the previous PR first and this one will be around 100 LOC.
=> Metrics support pt2

Package.swift, README.md
Made iOS 13 the new old minimum again (as it was in 0.0.6)
Closes #39 Min Version iOS 13
=> Make iOS 13 min Version again

Sources/UnleashProxyClientSwift/Metrics.swift, Sources/UnleashProxyClientSwift/UnleashProxyClientSwift.swift, UnleashProxyClientSwift.podspec
Should stop metrics same as poller.
Closes https://github.com/Unleash/unleash-proxy-client-swift/issues/44
=> fix: stop metrics

Package.swift, Sources/UnleashProxyClientSwift/Metrics.swift, Sources/UnleashProxyClientSwift/UnleashProxyClientSwift.swift, Tests/UnleashProxyClientSwiftTests/MetricsTests.swift, Tests/UnleashProxyClientSwiftTests/MockMetrics.swift, UnleashProxyClientSwift.podspec
Replace async/await with completion handlers to support ios12
=> feat: ios12 support

Sources/UnleashProxyClientSwift/Metrics.swift, Sources/UnleashProxyClientSwift/UnleashProxyClientSwift.swift, UnleashProxyClientSwift.podspec
=> fix: sync bucket access

Sources/UnleashProxyClientSwift/Poller.swift
`Poller.getFeatures()` doesn't always call its callback parameter. That leads to a leaked continuation error, if the whole fetching process gets wrapped in an async construct by sdk users (i.e. `withCheckedContinuation`).
It looks like a lot of changes - but that is only because the first if-clause in the `session.perform` callback got rewritten as a guard statement. Therefor, Git marks everything in the block as changed.
https://github.com/Unleash/unleash-proxy-client-swift/issues/56
=>  Fix Poller.getFeatures() not always calling its callback param 

UnleashProxyClientSwift.podspec
Updates podspec with version and description
=> chore: update podspec

UnleashProxyClientSwift.podspec
* Releases a patch release with the unsubscribe method
=> fix: podspec version

Sources/UnleashProxyClientSwift/Poller.swift, UnleashProxyClientSwift.podspec
You can inject your own poller that has custom implementation of the StorageProvider protocol. By default we provide in-memory implementation but any user of the SDK can use whatever local storage mechanism they want.
When constructing UnleashProxyClientSwift you need to inject `Poller(refreshInterval: refreshInterval, unleashUrl: url, apiKey: clientKey, session: URLSession.shared, storageProvider: yourStorageProvideImpl)`
=> feat: configurable storage

Sources/UnleashProxyClientSwift/Poller.swift, Sources/UnleashProxyClientSwift/UnleashProxyClientSwift.swift, Tests/UnleashProxyClientSwiftTests/MockPoller.swift, UnleashProxyClientSwift.podspec
=> fix: use storage provider

Tests/UnleashProxyClientSwiftTests/UnleashClientIntegrationTest.swift
=> test: integration test

Tests/UnleashProxyClientSwiftTests/UnleashClientIntegrationTest.swift
Testing disabling of the toggle
=> Improved integration test

Tests/UnleashProxyClientSwiftTests/UnleashClientIntegrationTest.swift
Modified the integration test that now starts with a feature in a disabled state (due to context settings) and then goes to enabled state (due to another context update).
Here's the API settings for the toggle used in this test:
Also added test for variant when the toggle is enabled. Here's the settings for the variant (at the strategy level):
=> test: update context happy path

Sources/UnleashProxyClientSwift/UnleashProxyClientSwift.swift, Tests/UnleashProxyClientSwiftTests/PollerTests.swift
Support empty variants returned from the frontend API.
Fixes: https://github.com/Unleash/unleash-proxy-client-swift/issues/83
=> fix: accept empty variants

UnleashProxyClientSwift.podspec
=> chore: version bump

README.md, Sources/UnleashProxyClientSwift/Metrics.swift, Sources/UnleashProxyClientSwift/Poller.swift, Sources/UnleashProxyClientSwift/UnleashProxyClientSwift.swift, Tests/UnleashProxyClientSwiftTests/MockPoller.swift, Tests/UnleashProxyClientSwiftTests/PollerTests.swift, UnleashProxyClientSwift.podspec
* use consistent name for custom headers with other frontend SDKs
* updated docs to describe the new option
* updated proxy to edge/proxy
* added test for custom headers
* podspec version bump
=> refactor: rename custom headers

Tests/UnleashProxyClientSwiftTests/PollerTests.swift
Poller signature has changed and one poller test added concurrently needs ot be updated
=> fix: timer test

README.md, Sources/UnleashProxyClientSwift/Metrics/Metrics.swift, Sources/UnleashProxyClientSwift/Poller/Poller.swift, Sources/UnleashProxyClientSwift/Version/Version.swift, Tests/UnleashProxyClientSwiftTests/PollerTests.swift
x- headers are deprecated (https://datatracker.ietf.org/doc/html/rfc6648). Let's use unleash- instead.
=> fix: drop x prefix

README.md, Sources/UnleashProxyClientSwift/Client/UnleashProxyClientSwift.swift, Sources/UnleashProxyClientSwift/Poller/CustomHeadersProvider.swift, Sources/UnleashProxyClientSwift/Poller/DefaultCustomHeadersProvider.swift, Sources/UnleashProxyClientSwift/Poller/Poller.swift, Tests/UnleashProxyClientSwiftTests/PollerTests.swift
This adds `customHeadersProvider` that allows you to dynamically set custom headers.
Closes #105
=> feat: add customHeadersProvider

README.md, Sources/UnleashProxyClientSwift/Version/Version.swift
Bumping version to 1.7.0. 
Readme update to remove Bearer since more typical usage is Authorization: token.
=> chore: version bump and docs update

README.md
Add docs about upcoming 2.0.0 major release.
=> docs: add migration guide and highlight what changed

Sources/UnleashProxyClientSwift/Version/Version.swift
=> chore: version bump for HTTP headers

README.md, UnleashProxyClientSwift.podspec
Documenting release process to cocoapods with the older dependency on event bus.
Updating podspec version to match swift package manager version.
=> chore: update release process to cocoapods and bump podspec
